<a href="https://colab.research.google.com/github/Pongpang-2102/Linear-Algebra-for-Data-Science_KDAI-Project/blob/main/ClassLecture_SparseMatrix_Linear_Algebra_Lab_(30_Oct_22).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# sparse matrix

from numpy import array
from scipy.sparse import csr_matrix



In [ ]:
# create dense matrix
A = array([ [1,0,0,1,0,0],
            [0,0,2,0,0,1],
            [0,0,0,2,0,0]  ])

In [ ]:
print(A)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]


In [ ]:
S = csr_matrix(A)


In [ ]:
print(S)

  (0, 0)	1
  (0, 3)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	2


In [ ]:
B = S.todense()

In [ ]:
print(B)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]


In [ ]:
import numpy
# calculate sparsity
sparsity = 1.0 - numpy.count_nonzero(A) / A.size

In [ ]:
print(sparsity)

0.7222222222222222


## Ordinal Encoder Class

In [ ]:
from numpy import asarray 
from sklearn.preprocessing import OrdinalEncoder , OneHotEncoder

In [ ]:
# define data
data = asarray( [ ['red'],['green'],['blue'] ]  )
print (data)

[['red']
 ['green']
 ['blue']]


In [ ]:
# define ordninal encoding 
encoder = OrdinalEncoder()
encoder

OrdinalEncoder()

In [ ]:
# transform data
result =  encoder.fit_transform(data)
print(result)

[[2.]
 [1.]
 [0.]]


## One-Hot Encoder

In [ ]:
# define one hot encoder
onehot_encoder = OneHotEncoder(sparse = False)

In [ ]:
# data transformation for one hot encoder
# show result for one hot encoder
result_v2 = onehot_encoder.fit_transform(data)
result_v2

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

## Dummy Variable Encoding
- from previous example of one-Hot Encoder

In [ ]:
# example of a dummy variable encoding
from numpy import asarray
from sklearn.preprocessing import OneHotEncoder

In [ ]:
# define data
data_new = asarray([['red'],['green'],['blue']])
print(data_new)

[['red']
 ['green']
 ['blue']]


In [ ]:
# define one hot encoding from our existed data
encoder_onehot_dummyvar = OneHotEncoder (drop = 'first' , sparse = False)

# transform data
onehot = encoder_onehot_dummyvar.fit_transform(data_new)
print(onehot)

[[0. 1.]
 [1. 0.]
 [0. 0.]]


In [ ]:
!pip list -v

Package                       Version                Location                               Installer
----------------------------- ---------------------- -------------------------------------- ---------
absl-py                       1.3.0                  /usr/local/lib/python3.7/dist-packages pip
aeppl                         0.0.33                 /usr/local/lib/python3.7/dist-packages pip
aesara                        2.7.9                  /usr/local/lib/python3.7/dist-packages pip
aiohttp                       3.8.3                  /usr/local/lib/python3.7/dist-packages pip
aiosignal                     1.2.0                  /usr/local/lib/python3.7/dist-packages pip
alabaster                     0.7.12                 /usr/local/lib/python3.7/dist-packages pip
albumentations                1.2.1                  /usr/local/lib/python3.7/dist-packages pip
altair                        4.2.0                  /usr/local/lib/python3.7/dist-packages pip
appdirs                     